cask_args appdir: "/Applications"

tap "fullscreen/tap"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/cask-versions"
tap "alecthomas/homebrew-tap"

# Tools
brew 'awscli'
brew 'awsebcli'
brew 'aws-rotate-key'
cask 'adoptopenjdk8'
brew 'cfn-lint'
brew 'elasticsearch'
brew 'exercism'
brew 'htop'
brew 'kops'
brew 'node'
brew 'openvpn'
brew 'shellcheck'
brew 'terraform'
brew 'zsh'
brew 'zsh-completions'
brew 'zsh-autosuggestions'

# Go Tools
brew "go"
brew "gometalinter"

# Applications
cask "docker"
cask "firefox"
cask "flux"
cask "google-chrome"
cask 'iterm2'
cask 'ngrok'
cask 'nordvpn'
cask 'postman'
cask 'slack-beta'
cask 'spectacle'
cask 'spotify'
cask "visual-studio-code"
# cask 'virtualbox' # This seems to always fail TODO
cask 'vlc'
cask 'zoomus'
