cask_args appdir: "/Applications"

tap "homebrew/cask"
tap "homebrew/core"

# Tools
brew 'awscli'
brew 'awsebcli'
brew "docker"
brew "docker-machine"
brew 'exercism'
brew "go"
brew 'htop'
brew 'kops'
brew 'node'
brew 'terraform'
brew 'zsh'
brew 'zsh-completions'

# Applications
cask "firefox"
cask "flux"
cask "google-chrome"
cask 'iterm2'
cask "minikube"
cask 'ngrok'
cask 'postman'
cask 'slack-beta'
cask 'spectacle'
cask "visual-studio-code"
cask 'virtualbox'
cask 'vlc'
